name: Publish Weather App
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: CI=true yarn test

  setup_gcp:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setup gcloud"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

  build:
    needs: [test, setup_gcp]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building!"
      - name: Build React App and server
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app
      - name: Build server
        run: |
          cd server && gcloud builds submit \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app-api

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying!"
      - name: Deploy React app
        run: |
          gcloud run deploy weather-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
      - name: Deploy server
        run: |
          gcloud run deploy weather-app-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/weather-app-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }},GOOGLE_PLACES_API_KEY=${{ secrets.GOOGLE_PLACES_API_KEY }}"
